// arena.js
//
// Tournament engine — students DO NOT edit this file.
//
// How it works:
//   1. tournament() receives an array of Monster instances
//   2. It simulates every bout (round-robin) and records the full event log
//   3. It then plays back the log with delays, firing CustomEvents the UI listens to
//
// Why separate simulation from playback?
// Because DOM animations are async (setTimeout), but game logic should be
// deterministic and instant. Simulating first keeps the logic clean.

// ── Timing constants (ms) ──
const ATTACK_DELAY   = 700;   // pause between individual attacks
const BOUT_DELAY     = 1800;  // pause before next bout starts
const SPECIAL_DELAY  = 400;   // extra pause when a special ability fires

// ── Event helpers ──

function emit(name, detail) {
  document.dispatchEvent(new CustomEvent(`arena:${name}`, { detail }));
}

// ── Bout simulation ──

/**
 * Simulate a single bout between two monsters.
 * Returns an array of event objects describing everything that happened.
 *
 * @param {Monster} a
 * @param {Monster} b
 * @returns {{ events: object[], winner: Monster }}
 */
function simulateBout(a, b) {
  const events = [];
  let turn = 0;

  // Guard: max 200 turns to prevent infinite loops with immortal builds
  while (a.isAlive() && b.isAlive() && turn < 200) {
    const attacker = turn % 2 === 0 ? a : b;
    const defender = turn % 2 === 0 ? b : a;

    const result = attacker.attack(defender);

    events.push({
      type: 'attack',
      attackerName: attacker.name,
      defenderName: defender.name,
      damage: result.damage,
      defenderHp: defender.hp.current,
      defenderMaxHp: defender.hp.max,
      defenderPct: defender.hp.percentage,
      attackerSide: attacker === a ? 'left' : 'right',
    });

    if (result.special) {
      events.push({
        type: 'special',
        attackerName: attacker.name,
        description: result.special,
        defenderHp: defender.hp.current,
        defenderMaxHp: defender.hp.max,
        defenderPct: defender.hp.percentage,
        attackerSide: attacker === a ? 'left' : 'right',
      });
    }

    turn++;
  }

  const winner = a.isAlive() ? a : b;
  events.push({ type: 'boutEnd', winnerName: winner.name });
  return { events, winner };
}

// ── Tournament ──

/**
 * Run a round-robin tournament.
 * Every monster fights every other monster exactly once.
 *
 * @param {Monster[]} monsters
 */
export function tournament(monsters) {
  if (monsters.length < 2) {
    console.error('Need at least 2 monsters for a tournament.');
    return;
  }

  // ── Phase 1: simulate all bouts, collect full event log ──
  const allEvents = [];
  const wins = Object.fromEntries(monsters.map(m => [m.name, 0]));

  for (let i = 0; i < monsters.length; i++) {
    for (let j = i + 1; j < monsters.length; j++) {
      const a = monsters[i];
      const b = monsters[j];

      // Reset both before the bout
      a.reset();
      b.reset();

      allEvents.push({
        type: 'boutStart',
        aName: a.name,
        bName: b.name,
        aImagePath: a.imagePath,
        bImagePath: b.imagePath,
        aMaxHp: a.hp.max,
        bMaxHp: b.hp.max,
      });

      const { events, winner } = simulateBout(a, b);
      allEvents.push(...events);
      wins[winner.name]++;

      allEvents.push({ type: 'boutPause' }); // breathing room between bouts
    }
  }

  // Build leaderboard
  const leaderboard = Object.entries(wins)
    .map(([name, w]) => ({ name, wins: w }))
    .sort((a, b) => b.wins - a.wins);

  allEvents.push({ type: 'tournamentEnd', leaderboard });

  // ── Phase 2: play back events with delays ──
  playback(allEvents);
}

// ── Playback ──

function playback(events) {
  let delay = 0;

  for (const event of events) {
    switch (event.type) {
      case 'boutStart':
        setTimeout(() => emit('boutStart', event), delay);
        delay += BOUT_DELAY;
        break;

      case 'attack':
        setTimeout(() => emit('attack', event), delay);
        delay += ATTACK_DELAY;
        break;

      case 'special':
        setTimeout(() => emit('special', event), delay);
        delay += SPECIAL_DELAY;
        break;

      case 'boutEnd':
        setTimeout(() => emit('boutEnd', event), delay);
        delay += BOUT_DELAY;
        break;

      case 'boutPause':
        delay += BOUT_DELAY;
        break;

      case 'tournamentEnd':
        setTimeout(() => emit('tournamentEnd', event), delay);
        break;
    }
  }
}
