// ui.js
//
// Arena UI — listens to CustomEvents from arena.js and updates the DOM.
// Students DO NOT edit this file.

import gsap from 'gsap';

// ── DOM refs ──
const boutLabel    = document.getElementById('bout-label');
const imgLeft      = document.getElementById('img-left');
const imgRight     = document.getElementById('img-right');
const nameLeft     = document.getElementById('name-left');
const nameRight    = document.getElementById('name-right');
const barLeft      = document.getElementById('bar-left');
const barRight     = document.getElementById('bar-right');
const hpLeft       = document.getElementById('hp-left');
const hpRight      = document.getElementById('hp-right');
const log          = document.getElementById('log');
const leaderboard  = document.getElementById('leaderboard');
const lbList       = document.getElementById('leaderboard-list');
const fighterLeft  = document.getElementById('fighter-left');
const fighterRight = document.getElementById('fighter-right');
const closeBtn     = document.getElementById('leaderboard-close');

// ── Helpers ──

function barColor(pct) {
  if (pct > 60) return '#4caf50';
  if (pct > 30) return '#ffc107';
  return '#f44336';
}

function updateBar(side, hp, maxHp, pct) {
  const bar  = side === 'left' ? barLeft  : barRight;
  const hpEl = side === 'left' ? hpLeft   : hpRight;
  gsap.to(bar, {
    width: `${pct}%`,
    backgroundColor: barColor(pct),
    duration: 0.4,
    ease: 'power2.out',
  });
  hpEl.textContent = `${hp} / ${maxHp}`;
}

function addLog(text, cls) {
  const li = document.createElement('li');
  li.className = cls;
  li.textContent = text;
  log.appendChild(li);
  log.parentElement.scrollTop = log.parentElement.scrollHeight;
}

function shakeCard(side) {
  const card = side === 'left' ? fighterLeft : fighterRight;
  gsap.fromTo(card,
    { x: -6 },
    { x: 6, duration: 0.08, repeat: 3, yoyo: true, ease: 'none',
      onComplete: () => gsap.set(card, { x: 0 }) }
  );
}

function glowCard(side) {
  const card = side === 'left' ? fighterLeft : fighterRight;
  card.classList.add('glow');
  gsap.fromTo(card,
    { boxShadow: '0 0 30px rgba(233,69,96,0.9)' },
    { boxShadow: '0 0 0px rgba(233,69,96,0)', duration: 0.8, ease: 'power2.out',
      onComplete: () => card.classList.remove('glow') }
  );
}

// ── Event handlers ──

document.addEventListener('arena:boutStart', ({ detail: d }) => {
  boutLabel.textContent = `⚔️  ${d.aName}  vs  ${d.bName}`;

  imgLeft.src   = d.aImagePath;  imgLeft.alt   = d.aName;
  imgRight.src  = d.bImagePath;  imgRight.alt  = d.bName;
  nameLeft.textContent  = d.aName;
  nameRight.textContent = d.bName;

  // Reset bars to full
  gsap.set(barLeft,  { width: '100%', backgroundColor: '#4caf50' });
  gsap.set(barRight, { width: '100%', backgroundColor: '#4caf50' });
  hpLeft.textContent  = `${d.aMaxHp} / ${d.aMaxHp}`;
  hpRight.textContent = `${d.bMaxHp} / ${d.bMaxHp}`;

  addLog(`── ${d.aName} vs ${d.bName} ──`, 'divider');
});

document.addEventListener('arena:attack', ({ detail: d }) => {
  const defSide = d.attackerSide === 'left' ? 'right' : 'left';
  shakeCard(d.attackerSide);
  updateBar(defSide, d.defenderHp, d.defenderMaxHp, d.defenderPct);
  addLog(`${d.attackerName} attacks ${d.defenderName} for ${d.damage} damage`, 'attack');
});

document.addEventListener('arena:special', ({ detail: d }) => {
  glowCard(d.attackerSide);
  const defSide = d.attackerSide === 'left' ? 'right' : 'left';
  updateBar(defSide, d.defenderHp, d.defenderMaxHp, d.defenderPct);
  addLog(d.description, 'special');
});

document.addEventListener('arena:boutEnd', ({ detail: d }) => {
  if (d.isDraw) {
    addLog(`🤝 Draw! No points awarded.`, 'bout');
  } else {
    addLog(`🏅 ${d.winnerName} wins the bout!`, 'bout');
  }
});

document.addEventListener('arena:tournamentEnd', ({ detail: d }) => {
  // Build leaderboard list
  lbList.innerHTML = '';
  d.leaderboard.forEach(({ name, wins }, i) => {
    const li = document.createElement('li');
    const medal = ['🥇', '🥈', '🥉'][i] ?? `${i + 1}.`;
    li.innerHTML = `<span>${medal} ${name}</span><span>${wins} win${wins !== 1 ? 's' : ''}</span>`;
    lbList.appendChild(li);
  });

  // Show leaderboard overlay
  leaderboard.classList.add('visible');
  leaderboard.setAttribute('aria-hidden', 'false');
  gsap.fromTo(leaderboard,
    { opacity: 0 },
    { opacity: 1, duration: 0.6, ease: 'power2.out' }
  );
  gsap.fromTo('.leaderboard-card',
    { y: 40, opacity: 0 },
    { y: 0, opacity: 1, duration: 0.6, delay: 0.2, ease: 'back.out(1.4)' }
  );
});

// Close button
closeBtn.addEventListener('click', () => {
  gsap.to(leaderboard, {
    opacity: 0,
    duration: 0.3,
    onComplete: () => {
      leaderboard.classList.remove('visible');
      leaderboard.setAttribute('aria-hidden', 'true');
    },
  });
});
