// arena.js — tournament engine. Students do not edit this file.
//
// Two-phase design:
//   1. Simulate all bouts instantly (deterministic, no async)
//   2. Play back the event log with delays (async, drives the UI)

const ATTACK_DELAY = 700;
const BOUT_DELAY = 1800;
const SPECIAL_DELAY = 400;

function emit(name, detail) {
  document.dispatchEvent(new CustomEvent(`arena:${name}`, { detail }));
}

function simulateBout(a, b) {
  const events = [];
  let turn = 0;

  // Coin flip — first attacker varies each bout even with identical builds.
  const goesFirst = Math.random() < 0.5 ? a : b;
  const goesSecond = goesFirst === a ? b : a;

  // 200-turn cap prevents infinite loops with immortal builds.
  while (a.isAlive() && b.isAlive() && turn < 200) {
    const attacker = turn % 2 === 0 ? goesFirst : goesSecond;
    const defender = turn % 2 === 0 ? goesSecond : goesFirst;
    const result = attacker.attack(defender);

    events.push({
      type: 'attack',
      attackerName: attacker.name,
      defenderName: defender.name,
      damage: result.damage,
      defenderHp: defender.hp.current,
      defenderMaxHp: defender.hp.max,
      defenderPct: defender.hp.percentage,
      attackerSide: attacker === a ? 'left' : 'right',
    });

    if (result.special) {
      events.push({
        type: 'special',
        attackerName: attacker.name,
        description: result.special,
        defenderHp: defender.hp.current,
        defenderMaxHp: defender.hp.max,
        defenderPct: defender.hp.percentage,
        attackerHp: attacker.hp.current,
        attackerMaxHp: attacker.hp.max,
        attackerPct: attacker.hp.percentage,
        attackerSide: attacker === a ? 'left' : 'right',
      });
    }

    turn++;
  }

  let winner = null;
  if (a.isAlive() && !b.isAlive()) winner = a;
  else if (b.isAlive() && !a.isAlive()) winner = b;

  events.push({ type: 'boutEnd', winnerName: winner ? winner.name : null, isDraw: winner === null });
  return { events, winner, firstAttacker: goesFirst };
}

/**
 * Run a round-robin tournament — every monster fights every other monster once.
 * @param {Monster[]} monsters
 */
export function tournament(monsters) {
  if (monsters.length < 2) {
    const label = document.getElementById('bout-label');
    if (label) label.textContent = '⚠️ Need at least 2 monsters to start the tournament!';
    console.error('Need at least 2 monsters for a tournament.');
    return;
  }

  const allEvents = [];
  const wins = Object.fromEntries(monsters.map((m) => [m.name, 0]));

  for (let i = 0; i < monsters.length; i++) {
    for (let j = i + 1; j < monsters.length; j++) {
      const a = monsters[i];
      const b = monsters[j];

      a.reset();
      b.reset();

      // Simulate before building boutStart so firstAttacker is available.
      const { events, winner, firstAttacker } = simulateBout(a, b);

      allEvents.push({
        type: 'boutStart',
        aName: a.name,
        bName: b.name,
        aImagePath: a.imagePath,
        bImagePath: b.imagePath,
        aMaxHp: a.hp.max,
        bMaxHp: b.hp.max,
        firstAttacker: firstAttacker.name,
      });

      allEvents.push(...events);
      if (winner) wins[winner.name]++;

      allEvents.push({ type: 'boutPause' });
    }
  }

  const leaderboard = Object.entries(wins)
    .map(([name, w]) => ({ name, wins: w }))
    .sort((a, b) => b.wins - a.wins);

  allEvents.push({ type: 'tournamentEnd', leaderboard });

  monsters.forEach((m) => m.reset());

  playback(allEvents);
}

function playback(events) {
  let delay = 0;

  for (const event of events) {
    switch (event.type) {
      case 'boutStart':
        setTimeout(() => emit('boutStart', event), delay);
        delay += BOUT_DELAY;
        break;
      case 'attack':
        setTimeout(() => emit('attack', event), delay);
        delay += ATTACK_DELAY;
        break;
      case 'special':
        setTimeout(() => emit('special', event), delay);
        delay += SPECIAL_DELAY;
        break;
      case 'boutEnd':
        setTimeout(() => emit('boutEnd', event), delay);
        delay += BOUT_DELAY;
        break;
      case 'boutPause':
        delay += BOUT_DELAY;
        break;
      case 'tournamentEnd':
        setTimeout(() => emit('tournamentEnd', event), delay);
        break;
    }
  }
}
