// ui.js — arena UI. Students do not edit this file.

import gsap from 'gsap';

const boutLabel = document.getElementById('bout-label');
const imgLeft = document.getElementById('img-left');
const imgRight = document.getElementById('img-right');
const nameLeft = document.getElementById('name-left');
const nameRight = document.getElementById('name-right');
const barLeft = document.getElementById('bar-left');
const barRight = document.getElementById('bar-right');
const hpLeft = document.getElementById('hp-left');
const hpRight = document.getElementById('hp-right');
const log = document.getElementById('log');
const leaderboard = document.getElementById('leaderboard');
const lbList = document.getElementById('leaderboard-list');
const fighterLeft = document.getElementById('fighter-left');
const fighterRight = document.getElementById('fighter-right');
const closeBtn = document.getElementById('leaderboard-close');
const headerRestartBtn = document.getElementById('header-restart-btn');
const startScreen = document.getElementById('start-screen');
const startRoster = document.getElementById('start-roster');

const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const prevHp = { left: null, right: null };

function barColor(pct) {
  if (pct > 60) return '#39ff14';
  if (pct > 30) return '#ffd700';
  return '#ff2020';
}

function updateBar(side, hp, maxHp, pct) {
  const bar  = side === 'left' ? barLeft  : barRight;
  const hpEl = side === 'left' ? hpLeft   : hpRight;
  const card = side === 'left' ? fighterLeft : fighterRight;
  // Kill in-flight tween so back-to-back updates start cleanly.
  gsap.killTweensOf(bar, 'width');
  gsap.to(bar, { width: `${pct}%`, backgroundColor: barColor(pct), duration: 0.4, ease: 'power2.out' });
  hpEl.textContent = `${hp} / ${maxHp}`;
  card.classList.toggle('low-hp', pct <= 30);
}

function addLog(text, cls) {
  const li = document.createElement('li');
  li.className = cls;
  li.textContent = text;
  log.appendChild(li);
  log.parentElement.scrollTop = log.parentElement.scrollHeight;
}

function hitFlash(side) {
  if (prefersReducedMotion) return;
  const card = side === 'left' ? fighterLeft : fighterRight;
  gsap.timeline()
    .to(card, { backgroundColor: 'rgba(255,255,255,0.35)', duration: 0.06, ease: 'none' })
    .to(card, { backgroundColor: '', duration: 0.12, ease: 'power2.out', clearProps: 'backgroundColor' });
}

function spawnDamageNumber(side, damage, isSpecial) {
  if (prefersReducedMotion || !damage) return;
  const card = side === 'left' ? fighterLeft : fighterRight;
  const el = document.createElement('div');
  el.className = `damage-number ${isSpecial ? 'special' : damage > 30 ? 'crit' : 'normal'}`;
  el.textContent = `-${damage}`;
  el.setAttribute('aria-hidden', 'true');
  const w = card.offsetWidth;
  el.style.left = `${Math.random() * w * 0.5 + w * 0.25}px`;
  el.style.top = '80px';
  card.appendChild(el);
  gsap.fromTo(el,
    { opacity: 1, y: 0, scale: 1.2 },
    { opacity: 0, y: -55, scale: 0.8, duration: 0.85, ease: 'power1.out', onComplete: () => el.remove() }
  );
}

function shakeCard(side) {
  const card = side === 'left' ? fighterLeft : fighterRight;
  gsap.killTweensOf(card, 'x');
  gsap.set(card, { x: 0 });
  gsap.fromTo(card, { x: -6 }, { x: 6, duration: 0.08, repeat: 3, yoyo: true, ease: 'none', onComplete: () => gsap.set(card, { x: 0 }) });
}

function glowCard(side) {
  const card  = side === 'left' ? fighterLeft : fighterRight;
  const color = side === 'left' ? '0,255,255' : '255,0,255';
  gsap.killTweensOf(card, 'boxShadow');
  gsap.fromTo(card,
    { boxShadow: `0 0 40px rgba(${color},1), 0 0 80px rgba(${color},0.6)` },
    { boxShadow: `0 0 10px rgba(${color},0.2)`, duration: 0.9, ease: 'power2.out' }
  );
}

function vsFlash(aName, bName) {
  if (prefersReducedMotion) return;
  const overlay   = document.getElementById('vs-overlay');
  const vsText    = document.getElementById('vs-text');
  const nameLeft  = document.getElementById('vs-name-left');
  const nameRight = document.getElementById('vs-name-right');
  nameLeft.textContent  = aName;
  nameRight.textContent = bName;
  gsap.killTweensOf([overlay, vsText, nameLeft, nameRight]);
  gsap.set(overlay,   { opacity: 0 });
  gsap.set(vsText,    { scale: 2.5, opacity: 0 });
  gsap.set(nameLeft,  { opacity: 0, y: -10 });
  gsap.set(nameRight, { opacity: 0, y:  10 });
  gsap.timeline()
    .to(overlay,   { opacity: 1, duration: 0.15 })
    .to(vsText,    { scale: 1, opacity: 1, duration: 0.25, ease: 'back.out(3)' }, '<')
    .to(nameLeft,  { opacity: 1, y: 0, duration: 0.2, ease: 'power2.out' }, '-=0.1')
    .to(nameRight, { opacity: 1, y: 0, duration: 0.2, ease: 'power2.out' }, '<')
    .to({},        { duration: 0.5 })
    .to(overlay,   { opacity: 0, duration: 0.2, ease: 'power2.in' })
    .to(vsText,    { opacity: 0, scale: 0.8, duration: 0.2 }, '<');
}

function victoryPulse(winnerSide) {
  if (prefersReducedMotion || !winnerSide) return;
  const card  = winnerSide === 'left' ? fighterLeft : fighterRight;
  const color = winnerSide === 'left' ? '0,255,255' : '255,0,255';
  gsap.killTweensOf(card, 'scale,boxShadow');
  gsap.timeline()
    .to(card, { scale: 1.04, boxShadow: `0 0 30px rgba(${color},0.9)`, duration: 0.3, ease: 'power2.out' })
    .to(card, { scale: 1.02, boxShadow: `0 0 15px rgba(${color},0.5)`, duration: 0.3, yoyo: true, repeat: 2 })
    .to(card, { scale: 1,    boxShadow: `0 0 10px rgba(${color},0.2)`, duration: 0.3, clearProps: 'scale' });
}

function shakeArena() {
  if (prefersReducedMotion) return;
  const arena = document.querySelector('.arena');
  gsap.killTweensOf(arena, 'x,y');
  gsap.to(arena, {
    keyframes: [
      { x: -5, y:  3, duration: 0.05 },
      { x:  5, y: -4, duration: 0.05 },
      { x: -4, y:  2, duration: 0.05 },
      { x:  3, y: -3, duration: 0.05 },
      { x: -2, y:  1, duration: 0.05 },
      { x:  0, y:  0, duration: 0.05 },
    ],
    ease: 'none',
    onComplete: () => gsap.set(arena, { clearProps: 'x,y' })
  });
}

document.addEventListener('arena:boutStart', ({ detail: d }) => {
  const strikeNote = d.firstAttacker ? ` — ${d.firstAttacker} strikes first!` : '';
  boutLabel.textContent = `${d.aName}  vs  ${d.bName}${strikeNote}`;

  imgLeft.src = d.aImagePath;
  imgLeft.alt = d.aName;
  imgRight.src = d.bImagePath;
  imgRight.alt = d.bName;
  nameLeft.textContent = d.aName;
  nameRight.textContent = d.bName;

  fighterLeft.classList.remove('low-hp');
  fighterRight.classList.remove('low-hp');
  prevHp.left  = d.aMaxHp;
  prevHp.right = d.bMaxHp;

  gsap.set(barLeft, { width: '100%', backgroundColor: '#39ff14' });
  gsap.set(barRight, { width: '100%', backgroundColor: '#39ff14' });
  hpLeft.textContent = `${d.aMaxHp} / ${d.aMaxHp}`;
  hpRight.textContent = `${d.bMaxHp} / ${d.bMaxHp}`;

  addLog(`── ${d.aName} vs ${d.bName} ──`, 'divider');

  vsFlash(d.aName, d.bName);
  if (!prefersReducedMotion) {
    gsap.fromTo(fighterLeft,  { x: -40, opacity: 0 }, { x: 0, opacity: 1, duration: 0.4, ease: 'power2.out' });
    gsap.fromTo(fighterRight, { x:  40, opacity: 0 }, { x: 0, opacity: 1, duration: 0.4, ease: 'power2.out' });
  }
});

document.addEventListener('arena:attack', ({ detail: d }) => {
  const defSide = d.attackerSide === 'left' ? 'right' : 'left';
  const dmg = prevHp[defSide] !== null ? prevHp[defSide] - d.defenderHp : d.damage;
  prevHp[defSide] = d.defenderHp;
  shakeCard(d.attackerSide);
  hitFlash(defSide);
  spawnDamageNumber(defSide, dmg, false);
  updateBar(defSide, d.defenderHp, d.defenderMaxHp, d.defenderPct);
  addLog(`${d.attackerName} attacks ${d.defenderName} for ${d.damage} damage`, 'attack');
});

document.addEventListener('arena:special', ({ detail: d }) => {
  const defSide = d.attackerSide === 'left' ? 'right' : 'left';
  const dmg = prevHp[defSide] !== null ? prevHp[defSide] - d.defenderHp : 0;
  prevHp[defSide] = d.defenderHp;
  prevHp[d.attackerSide] = d.attackerHp;
  glowCard(d.attackerSide);
  shakeArena();
  hitFlash(defSide);
  spawnDamageNumber(defSide, dmg, true);
  updateBar(defSide, d.defenderHp, d.defenderMaxHp, d.defenderPct);
  updateBar(d.attackerSide, d.attackerHp, d.attackerMaxHp, d.attackerPct);
  addLog(d.description, 'special');
});

document.addEventListener('arena:boutEnd', ({ detail: d }) => {
  if (d.isDraw) {
    addLog('Draw! No points awarded.', 'bout');
  } else {
    addLog(`${d.winnerName} wins the bout!`, 'bout');
    const winnerSide = nameLeft.textContent === d.winnerName  ? 'left'
                     : nameRight.textContent === d.winnerName ? 'right'
                     : null;
    victoryPulse(winnerSide);
  }
});

document.addEventListener('arena:tournamentEnd', ({ detail: d }) => {
  lbList.innerHTML = '';
  d.leaderboard.forEach(({ name, wins }, i) => {
    const li = document.createElement('li');
    const medal = ['1ST', '2ND', '3RD'][i] ?? `${i + 1}.`;
    li.innerHTML = `<span>${medal} ${name}</span><span>${wins} win${wins !== 1 ? 's' : ''}</span>`;
    lbList.appendChild(li);
  });

  populateMonteCarlo();

  leaderboard.classList.add('visible');
  leaderboard.setAttribute('aria-hidden', 'false');
  gsap.fromTo(leaderboard, { opacity: 0 }, { opacity: 1, duration: 0.6, ease: 'power2.out' });
  gsap.fromTo('.leaderboard-card', { y: 40, opacity: 0 }, { y: 0, opacity: 1, duration: 0.6, delay: 0.2, ease: 'back.out(1.4)' });
  headerRestartBtn.hidden = false;
});

function closeLeaderboard() {
  gsap.to(leaderboard, {
    opacity: 0,
    duration: 0.3,
    onComplete: () => {
      leaderboard.classList.remove('visible');
      leaderboard.setAttribute('aria-hidden', 'true');
      gsap.set(leaderboard, { clearProps: 'opacity' });
    },
  });
}

closeBtn.addEventListener('click', closeLeaderboard);

function resetUI() {
  log.innerHTML = '';
  boutLabel.textContent = 'Waiting for the tournament to start...';
  fighterLeft.classList.remove('low-hp');
  fighterRight.classList.remove('low-hp');
  prevHp.left = null;
  prevHp.right = null;
  headerRestartBtn.hidden = true;
}

function doRestart() {
  closeLeaderboard();
  resetUI();
  window.startTournament();
}

document.getElementById('restart-btn').addEventListener('click', doRestart);
headerRestartBtn.addEventListener('click', doRestart);

// ── Start screen ──
document.getElementById('start-btn').addEventListener('click', () => {
  if (prefersReducedMotion) {
    startScreen.hidden = true;
  } else {
    gsap.to(startScreen, {
      opacity: 0, duration: 0.4, ease: 'power2.in',
      onComplete: () => { startScreen.hidden = true; },
    });
  }
  window.startTournament();
});

document.addEventListener('arena:roster', ({ detail: names }) => {
  startRoster.innerHTML = '';
  names.forEach(name => {
    const li = document.createElement('li');
    li.textContent = name;
    startRoster.appendChild(li);
  });
});

let _mcResults = null;

document.addEventListener('arena:montecarlo', ({ detail: results }) => {
  _mcResults = results;
});

function populateMonteCarlo() {
  if (!_mcResults) return;
  const list  = document.getElementById('montecarlo-list');
  const label = document.getElementById('montecarlo-label');
  label.textContent = '1 000 sim win rate';
  list.innerHTML = '';

  _mcResults.forEach(({ name, winRate }, i) => {
    const pct = Math.round(winRate * 100);
    const li = document.createElement('li');
    li.innerHTML = `
      <div class="mc-name-row">
        <span class="mc-name">${name}</span>
        <span class="mc-pct">${pct}%</span>
      </div>
      <div class="mc-bar-track">
        <div class="mc-bar-fill rank-${i + 1}" style="width:0%"></div>
      </div>`;
    list.appendChild(li);

    requestAnimationFrame(() => {
      li.querySelector('.mc-bar-fill').style.width = `${pct}%`;
    });
  });
}
